anica_ui/anica_ui/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('anica/', include('basic_ui.urls')),
    path('admin/', admin.site.urls),
]

anica_ui/basic_ui/urls.py
from django.urls import path

from . import views

app_name = 'basic_ui'
urlpatterns = [
    path('', views.start_view, name='start'),

    path('campaign/', views.all_campaigns_view, name='all_campaigns'),
    path('campaign/<int:campaign_id>/', views.single_campaign_view, name='single_campaign'),
    path('campaign/<int:campaign_id>/discoveries/', views.all_discoveries_view, name='all_discoveries'),
    path('campaign/<int:campaign_id>/discoveries/<str:discovery_id>/', views.single_discovery_view, name='single_discovery'),
    path('campaign/<int:campaign_id>/discoveries/<str:discovery_id>/witness', views.witness_view, name='witness'),
    path('campaign/<int:campaign_id>/measurements-overview/<int:meas_id>', views.measurements_overview_view, name='measurements_overview'),

    path('generalization/', views.all_generalizations_view, name='all_generalizations'),
    path('generalization/<int:generalization_id>/', views.single_generalization_view, name='single_generalization'),
    path('generalization/<int:generalization_id>/witness', views.gen_witness_view, name='gen_witness'),
    path('generalization/<int:generalization_id>/measurements/<int:meas_id>', views.gen_measurements_view, name='gen_measurements'),
    path('generalization/<int:generalization_id>/measurements-overview/<int:meas_id>', views.gen_measurements_overview_view, name='gen_measurements_overview'),
    path('generalization/<int:generalization_id>/absblock.json', views.generalization_json_view, name='generalization_json'),

    path('bbsets/', views.all_bbsets_view, name='all_bbsets'),
    path('bbsets/<int:bbset_id>', views.single_bbset_view, name='single_bbset'),
    path('bbsets/<int:bbset_id>/allbbs', views.single_bbset_allbbs_view, name='single_bbset_allbbs'),

    path('campaign/<int:campaign_id>/discoveries/<str:discovery_id>/absblock.json', views.discovery_json_view, name='discovery_json'),

    path('no-measurements', views.measurements_empty_view, name='measurements_empty'),
    path('campaign/<int:campaign_id>/measurements/<int:meas_id>', views.measurements_view, name='measurements'),


    path('campaign/<int:campaign_id>/insnschemes/', views.all_insnschemes_view, name='all_insnschemes'),
    path('campaign/<int:campaign_id>/insnschemes/<int:ischeme_id>/', views.single_insnscheme_view, name='single_insnscheme'),
]

anica_ui/basic_ui/views.py
import django
from django.core.cache import cache as CACHE
from django.db.models import F, Q, Sum, Avg, Count, Value
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404
from django.utils.safestring import mark_safe
from django.utils.html import escape
from django.utils.safestring import mark_safe

from pathlib import Path
import os
import urllib

import django_tables2 as tables
from markdown import markdown

from anica.abstractioncontext import AbstractionContext
from anica.bbset_coverage import make_heatmap
from iwho.configurable import config_diff, pretty_print

from .models import Campaign, Discovery, InsnScheme, Generalization, BasicBlockSet, BasicBlockSetMetrics, BasicBlockEntry
from .custom_pretty_printing import prettify_absblock, prettify_seconds, prettify_config_diff, prettify_abstraction_config, listify
from .witness_site import gen_witness_site, gen_measurement_site, get_witnessing_series_id
from .helpers import load_abstract_block

from .plots import *

def get_docs(site_name):
    # cached = CACHE.get(site_name, None)
    # if cached is not None:
    #     return cached

    base = Path(django.apps.apps.get_app_config('basic_ui').path)
    doc_file = base / 'inline_docs' / (site_name + '.md' )
    assert doc_file.is_file()

    with open(doc_file, 'r') as f:
        lines = f.readlines()
    title_line = lines[0]
    assert title_line[0] == '#'
    title = title_line[1:]
    body = "".join(lines[1:])

    body_html = mark_safe(markdown(body))

    res = { 'helptitle': title, 'helpcontent': body_html }

    # CACHE.set(site_name, res)

    return res

def url_with_querystring(path, **kwargs):
    return path + '?' + urllib.parse.urlencode(kwargs)

def tool_str_for(campaign_id):
    campaign_obj = get_object_or_404(Campaign, pk=campaign_id)
    tool_list = campaign_obj.tools.all()
    tool_str = " vs. ".join(map(str, tool_list))
    return tool_str

campaign_table_attrs = {"class": "campaigntable"}

def start_view(request):
    context = {
        "title": "Start",
        'topbarpathlist': [],
    }
    context.update(get_docs('start'))
    return render(request, "basic_ui/start.html",  context)

class CampaignTable(tables.Table):
    campaign_id = tables.Column(
            linkify=(lambda value: django.urls.reverse('basic_ui:single_campaign', kwargs={'campaign_id': value})),
            attrs={"td": campaign_table_attrs, "th": campaign_table_attrs},
            verbose_name="ID")
    tag = tables.Column(
            linkify=(lambda value: url_with_querystring(django.urls.reverse('basic_ui:all_campaigns'), tag=value)),
            attrs={"td": campaign_table_attrs, "th": campaign_table_attrs},
            verbose_name="Tag")
    date = tables.Column(attrs={"td": campaign_table_attrs, "th": campaign_table_attrs},
            verbose_name="Start Date")
    host_pc = tables.Column(attrs={"td": campaign_table_attrs, "th": campaign_table_attrs},
            verbose_name="Host PC", visible=False)
    tools = tables.Column(attrs={"td": campaign_table_attrs, "th": campaign_table_attrs},
            verbose_name="Tools under Investigation")
    config_delta = tables.Column(attrs={"td": campaign_table_attrs, "th": campaign_table_attrs},
            verbose_name="Config Delta")
    num_batches = tables.Column(attrs={"td": campaign_table_attrs, "th": campaign_table_attrs},
            verbose_name="# Batches")
    num_discoveries = tables.Column(attrs={"td": campaign_table_attrs, "th": campaign_table_attrs},
            verbose_name="# Discoveries")
    init_interesting_sample_ratio = tables.Column(attrs={"td": campaign_table_attrs, "th": campaign_table_attrs},
            verbose_name="IISR")
    time_spent = tables.Column(attrs={"td": campaign_table_attrs, "th": campaign_table_attrs},
            verbose_name="Run-Time")

    def render_time_spent(self, value):
        return prettify_seconds(value)

    class Meta:
        attrs = campaign_table_attrs
        row_attrs = campaign_table_attrs


def all_campaigns_view(request):
    topbarpathlist = [
            ('all campaigns', django.urls.reverse('basic_ui:all_campaigns')),
        ]

    tag_filter = request.GET.get('tag', None)
    if tag_filter is None:
        campaigns = Campaign.objects.all()
    else:
        campaigns = Campaign.objects.filter(tag=tag_filter)
        topbarpathlist.append((f"with tag '{tag_filter}'", url_with_querystring(django.urls.reverse('basic_ui:all_campaigns'), tag=tag_filter)))

    if len(campaigns) == 0:
        context = {
                "title": "All Campaigns",
                'topbarpathlist': topbarpathlist,
            }
        context.update(get_docs('all_campaigns'))
        return render(request, "basic_ui/all_campaigns_empty.html", context)

    assert len(campaigns) > 0

    base_config = AbstractionContext.get_default_config()
    config_deltas = []
    for campaign in campaigns:
        config_deltas.append(config_diff(base_config, campaign.config_dict))

    common_diffs = []
    for diff in config_deltas[0]:
        if all(map(lambda x: diff in x, config_deltas)):
            common_diffs.append(diff)

    for d in common_diffs:
        for delta in config_deltas:
            delta.remove(d)

    data = []
    for campaign, delta in zip(campaigns, config_deltas):
        num_batches = campaign.discoverybatch_set.count()
        num_discoveries = Discovery.objects.filter(batch__campaign=campaign).filter(subsumed_by=None).count()
        tool_list = campaign.tools.all()
        init_interesting_sample_ratio = None
        if num_batches > 0:
            init_batch = campaign.discoverybatch_set.order_by('pk').first()
            if init_batch.num_sampled > 0:
                init_interesting_sample_ratio = init_batch.num_interesting / init_batch.num_sampled

        config_delta_html = prettify_config_diff(delta)

        data.append({
            'campaign_id': campaign.id,
            'tag': campaign.tag,
            'tools': ", ".join(map(str, tool_list)),
            'config_delta': config_delta_html,
            'date': campaign.date,
            'host_pc': campaign.host_pc,
            'num_batches': num_batches,
            'num_discoveries': num_discoveries,
            'init_interesting_sample_ratio': init_interesting_sample_ratio,
            'time_spent': campaign.total_seconds,
            })

    table = CampaignTable(data)

    tables.RequestConfig(request).configure(table)


    context = {
        "title": "All Campaigns",
        "table": table,
        'topbarpathlist': topbarpathlist,
    }

    context.update(get_docs('all_campaigns'))

    return render(request, "basic_ui/all_campaigns.html",  context)



def single_campaign_view(request, campaign_id):
    campaign_obj = get_object_or_404(Campaign, pk=campaign_id)

    # get the batch-independent information
    tool_list = campaign_obj.tools.all()
    termination_condition = list(campaign_obj.termination_condition.items())
    cfg_str = prettify_abstraction_config(campaign_obj.config_dict)

    all_batches = campaign_obj.discoverybatch_set.all().order_by('batch_index')
    total_batches = all_batches.count()

    # Check whether we should make this view comparable with a different one
    # (i.e. make sure that all plot axes are the same and we use a common
    # prefix if not explicitly specified otherwise.)
    cmp_campaign_id_str = request.GET.get('compare_with', None)

    cmp_campaign_objs = []
    all_cmp_batches = []

    if cmp_campaign_id_str is not None:
        cmp_campaign_ids = cmp_campaign_id_str.split(',')
        for cmp_campaign_id in cmp_campaign_ids:
            try:
                cmp_campaign_id = int(cmp_campaign_id)
                curr_cmp_campaign_obj = Campaign.objects.get(pk=cmp_campaign_id)
                cmp_campaign_objs.append(curr_cmp_campaign_obj)
            except (ValueError, Campaign.DoesNotExist):
                raise Http404(f"Campaign {cmp_campaign_id} could not be found for comparison.")
            all_cmp_batches.append(curr_cmp_campaign_obj.discoverybatch_set.all().order_by('batch_index'))

    batch_pos_pre = total_batches

    # get the number of batches that we should use for this display
    batch_pos_str = request.GET.get('batch_pos', None)

    if batch_pos_str is None:
        batch_pos_explicitly_set = False
        batch_pos_str = batch_pos_pre
    else:
        batch_pos_explicitly_set = True

    if batch_pos_str == 'min':
        batch_pos = min(batch_pos_pre, *map(lambda x: x.count(), all_cmp_batches))
    else:
        try:
            batch_pos = int(batch_pos_str)
        except ValueError:
            batch_pos = batch_pos_pre

    # make sure that the position is in bounds
    if batch_pos <= 0:
        batch_pos = 1
    if batch_pos > total_batches:
        batch_pos = total_batches

    # restrict to the first batch_pos batches
    batches = all_batches[:batch_pos]

    cmp_batches = []
    cmp_discoveries = []
    for cmp_batch, cmp_campaign_obj in zip(all_cmp_batches, cmp_campaign_objs):
        if batch_pos_explicitly_set:
            cmp_batches.append(cmp_batch[:batch_pos])
            cmp_discoveries.append(Discovery.objects.filter(batch__campaign=cmp_campaign_obj, batch__batch_index__range=(0, batch_pos-1)))
        else:
            cmp_batches.append(cmp_batch)
            cmp_discoveries.append(Discovery.objects.filter(batch__campaign=cmp_campaign_obj))

    num_batches = batch_pos

    relevant_discoveries = Discovery.objects.filter(batch__campaign=campaign_obj, batch__batch_index__range=(0, batch_pos-1))
    num_discoveries = relevant_discoveries.count()

    relevant_discoveries = relevant_discoveries.filter(subsumed_by=None)

    num_discoveries_not_subsumed = relevant_discoveries.count()

    total_seconds = batches.aggregate(Sum('batch_time'))['batch_time__sum']
    time_spent = prettify_seconds(total_seconds)

    topbarpathlist = [

anica_ui/basic_ui/templates/basic_ui/all_campaigns.html
{% extends "basic_ui/base.html" %}

{% load django_tables2 %}

{% block title %}{{title}}{% endblock %}

{% block content %}
    {% render_table table %}

    <h3>Compare Campaigns</h3>

    Compare the following, space-separated campaign IDs: <input id="comparison_keys" onkeydown="handle_comparison_input()">

    <button id="make_comparison" onclick="open_comparison()">make comparison</button>

{% endblock %}

{% block extra_scripts %}
    <script type="text/javascript">
        function handle_comparison_input() {
            if(event.key === 'Enter') {
                open_comparison();
            }
        }
        function open_comparison() {
            const comparison_keys = document.getElementById("comparison_keys").value.trim().replace(/\s+|,/g, ' ');
            if (comparison_keys.length === 0) {
                    return;
            }
            base_url = window.location.href.split('?')[0];
            if (comparison_keys.length === 1) {
                const url = base_url + 'campaign/' + comparison_keys + '/';
                window.open(url, '_blank');
                return;
            }
            const all_ids = comparison_keys.split(' ');

            for (const curr_id of all_ids) {
                const copy = [...all_ids]
                const index = copy.indexOf(curr_id);
                if (index !== -1) {
                    copy.splice(index, 1);
                }

                const url = base_url + 'campaign/' + curr_id + '/?batch_pos=min&compare_with=' + copy.join(',');
                window.open(url, '_blank');
            }
        }
    </script>
{% endblock %}

anica_ui/basic_ui/templates/basic_ui/all_campaigns_empty.html
{% extends "basic_ui/base.html" %}

{% block title %}{{title}}{% endblock %}

{% block content %}
    No campaigns registered yet.<br>
    Go run and import some!
{% endblock %}

anica_ui/basic_ui/templates/basic_ui/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'basic_ui/style.css' %}">
    {% block stylesheets %}
    {% endblock %}
    <title>{% block title %}{% endblock %} - AnICA UI</title>
</head>

<script type="text/javascript">
function show_docs() {
    const container = document.getElementById("helpcontainer");
    container.style.display = "block";
}

function hide_docs() {
  const container = document.getElementById("helpcontainer");
    container.style.display = "none";
}
</script>

{% block extra_scripts %}
{% endblock %}

<body>
    <div id='topbar'>
        <div id='topbarbox'>
            <div id='topbarnamebox'>
                <a href="{% url 'basic_ui:start' %}" style="color:inherit;text-decoration:inherit;">AnICA Explorer</a>
            </div>
            <div id='topbarpathbox'>
                <span id='topbarpath'>
                {# {% block topbarpath %}{% endblock %} #}
                {% for entry, link in topbarpathlist %}
                    /
                    <a href="{{link}}">{{entry}}</a>
                {% endfor %}
                </span>
            </div>
            <div id='topbarbuttonbox'>
                <button id="help-open-button" onclick="show_docs()">Open Docs</button>
            </div>
        </div>
    </div>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
    <div id="helpcontainer" class="sidecontainer">
        <button id="help-close-button" onclick="hide_docs()">Close Docs</button>
        <h2>Feature Documentation: {{ helptitle }}</h2>
        {{ helpcontent }}
    </div>
</body>
</html>

anica_ui/basic_ui/templates/basic_ui/campaign_overview.html
{% extends "basic_ui/base.html" %}

{% load static %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'basic_ui/tooltips.css' %}">
{% endblock %}

{% block title %}Single Campaign{% endblock %}

{% block content %}
    <h3>Tools under Investigation:</h3>
        <ul>
            {% for tool in tool_list %}
                <li>{{tool.full_name}}</li>
            {% endfor %}
        </ul>

    <h3>Termination Condition:</h3>
        <ul>
            {% for condition, value in termination_condition %}
                <li><b>{{condition}}:</b> {{value}}</li>
            {% endfor %}
        </ul>

    <h3>Abstraction Config:</h3>
        {{ abstraction_config | safe }}

    <h3>Prefix Control:</h3>

    This page is currently only displaying results for the first <b>{{ batch_pos }}</b> out of <b>{{ total_batches }}</b> batches of the campaign.<br>

    To show the first <input type="number" id="new_batch_pos" min="1" max="{{ total_batches }}" value="{{ total_batches }}"> instead, click here: <button id="change_prefix" onclick="change_prefix()">change prefix</button>

    <h3>Result Summary:</h3>
    <table>
        {% for key, value in stats %}
            <tr>
                <td>{{key}}:</td><td>{{value}}</td>
            </tr>
        {% endfor %}
    </table>

    <h3>Plots:</h3>

    {% for plot in plots %}
        <div class="imagecontainer">
            <img src='data:image/png;base64,{{ plot }}'>
        </div>
    {% endfor %}

    The plots are currently{% if is_comparing %} scaled to be comparable with campaign(s) {{ cmp_campaign_ids }}{% else %} not scaled for comparison{% endif %}.<br>

    To change compare with campaign <input type="number" id="new_cmp_campaign" min="1", max="1000" value="1"> instead, click here: <button id="change_cmp_campaign" onclick="change_cmp_campaign()">change comparison</button> <br>

    {% if is_comparing %}
    To clear this, click here: <button id="clear_cmp_campaign" onclick="clear_cmp_campaign()">clear comparison</button>
    {% endif %}


    <h3>Detailed Results:</h3>
        <ul>
            <li><a href="{% url 'basic_ui:all_discoveries' campaign.id %}?sort=-generality">All Discoveries</a></li>
            <li><a href="{% url 'basic_ui:all_insnschemes' campaign.id %}">All occurring Instruction Schemes</a></li>
        </ul>

{% endblock %}


{% block extra_scripts %}
    <script type="text/javascript">
        function change_prefix() {
            const new_batch_pos = document.getElementById("new_batch_pos").value;

            if ('URLSearchParams' in window) {
                var searchParams = new URLSearchParams(window.location.search);
                searchParams.set("batch_pos", "" + new_batch_pos);
                window.location.search = searchParams.toString();
            }
        }

        function clear_cmp_campaign() {
            if ('URLSearchParams' in window) {
                var searchParams = new URLSearchParams(window.location.search);
                searchParams.delete("compare_with");
                window.location.search = searchParams.toString();
            }
        }
        function change_cmp_campaign() {
            const new_cmp_campaign = document.getElementById("new_cmp_campaign").value;

            if ('URLSearchParams' in window) {
                var searchParams = new URLSearchParams(window.location.search);
                searchParams.set("compare_with", "" + new_cmp_campaign);
                window.location.search = searchParams.toString();
            }
        }
    </script>
{% endblock %}

anica_ui/basic_ui/templates/basic_ui/discovery_overview.html
{% extends "basic_ui/base.html" %}

{% load static %}

{% load django_tables2 %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'basic_ui/tooltips.css' %}">
{% endblock %}

{% block title %}Single Discovery{% endblock %}

{% block content %}
    <h3>Discovery:</h3>
    <div style="display:flex;">
        <div style="flex: 0 0 50%;">
            <h4>Original Abstract Block: [<a href="{% url 'basic_ui:discovery_json' campaign_id discovery_id %}">raw json</a>] </h4>
            <div class="indent_content">
            {{ absblock | safe }}
            </div>

        </div>

        <div style="flex: 1;">
            <h4>Narrowed Abstract Block:</h4>
            <div class="indent_content">
            {{ min_absblock | safe }}
            </div>
        </div>
    </div>

    <h3>Example Results:</h3>

    {% if example_series_id != -1 %}
        <iframe id="measurement_overview_iframe" scrolling="no" src="{% url 'basic_ui:measurements_overview' campaign_id example_series_id %}">loading measurements...</iframe>

        <script>
            var iframe = document.getElementById("measurement_overview_iframe");
            iframe.onload = function(){
                iframe.style.height = (iframe.contentWindow.document.body.scrollHeight * 1.04) + 'px';
            }
        </script>
    {% else %}
        Not available.
    {% endif %}

    <h3>Remarks:</h3>
    <ul>
        {{ remark_text | safe }}
    </ul>

    <h3>Metrics:</h3>
    <table>
        {% for key, value in stats %}
            <tr>
                <td>{{key}}:</td><td>{{value}}</td>
            </tr>
        {% endfor %}
    </table>

    <h3>Plots:</h3>
    {% for plot in plots %}
        <div class="imagecontainer">
            <img src='data:image/png;base64,{{ plot }}'>
        </div>
    {% endfor %}

    <h3>Witness:</h3>
    <ul>
        <li>
            <a href='{% url 'basic_ui:witness' campaign_id discovery_id %}'>Click here to open.</a>
        </li>
    </ul>

    <h3>Related Generalizations:</h3>

    {% render_table table %}

{% endblock %}

anica_ui/basic_ui/templates/basic_ui/single_bbset.html
{% extends "basic_ui/base.html" %}

{% load django_tables2 %}

{% block title %}{{title}}{% endblock %}

{% block content %}
<h3>Results for Basic Block Set "{{ bbset_name }}": [<a href="{% url 'basic_ui:single_bbset_allbbs' bbset_id %}">view Basic Blocks</a>]</h3>

<h4>Interestingness Heatmap </h4>
    <div class="imagecontainer">
        <img src='data:image/png;base64,{{ plot }}'>
    </div>

<h4>Campaign Coverage Results</h4>
    {% render_table table %}
{% endblock %}

anica_ui/basic_ui/templates/basic_ui/single_generalization_view.html
{% extends "basic_ui/base.html" %}

{% load static %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'basic_ui/tooltips.css' %}">
{% endblock %}

{% block title %}Single Generalization{% endblock %}

{% block content %}
    <h3>Discovery:</h3>
    <div style="display:flex;">
        <div style="flex: 0 0 50%;">
            <h4>Original Abstract Block: [<a href="{% url 'basic_ui:generalization_json' generalization_id %}">raw json</a>] </h4>
            <div class="indent_content">
            {{ absblock | safe }}
            </div>

        </div>

        <div style="flex: 1;">
            <h4>Narrowed Abstract Block:</h4>
            <div class="indent_content">
            {{ min_absblock | safe }}
            </div>
        </div>
    </div>

    <h3>Example Results:</h3>

    {% if example_series_id != -1 %}
        <iframe id="measurement_overview_iframe" scrolling="no" src="{% url 'basic_ui:gen_measurements_overview' generalization_id example_series_id %}">loading measurements...</iframe>

        <script>
            var iframe = document.getElementById("measurement_overview_iframe");
            iframe.onload = function(){
                iframe.style.height = (iframe.contentWindow.document.body.scrollHeight * 1.04) + 'px';
            }
        </script>
    {% else %}
        Not available.
    {% endif %}

    <h3>Remarks:</h3>
    <ul>
        {{ remark_text | safe }}
    </ul>

    <h3>Metrics:</h3>
    <table>
        {% for key, value in stats %}
            <tr>
                <td>{{key}}:</td><td>{{value}}</td>
            </tr>
        {% endfor %}
    </table>

    <h3>Witness:</h3>
    <ul>
        <li>
            <a href='{% url 'basic_ui:gen_witness' generalization_id %}'>Click here to open.</a>
        </li>
    </ul>

    <h3>Abstraction Config:</h3>
        {{ abstraction_config | safe }}


{% endblock %}

anica_ui/basic_ui/templates/basic_ui/start.html
{% extends "basic_ui/base.html" %}

{% block title %}{{title}}{% endblock %}

{% block content %}
    <h3>Select a Task:</h3>
    <ol class="startlist">
        <li> <b><a style="color:inherit" href="{% url 'basic_ui:all_campaigns' %}">View registered AnICA discovery campaigns.</a></b> </li>
        <li> <b><a style="color:inherit" href="{% url 'basic_ui:all_generalizations' %}">View selected AnICA generalizations of interesting basic blocks.</a></b> </li>
        <li> <b><a style="color:inherit" href="{% url 'basic_ui:all_bbsets' %}">View coverage metrics of the discovery campaigns for specific sets of basic blocks.</a></b> </li>
    </ol>
{% endblock %}

anica_ui/basic_ui/templates/basic_ui/witness.html
{% extends "basic_ui/base.html" %}

{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'basic_ui/witness_style.css' %}">
{% endblock %}

{% block title %}Generalization Witness{% endblock %}

{% block content %}

<div class="graphcolumn">
<div class="gridcontainer">
    <svg xmlns="http://www.w3.org/2000/svg">
      <defs>
        <marker id="arrowhead" viewBox="0 0 10 10" refX="6" refY="5"
            markerWidth="6" markerHeight="6" fill="grey" stroke="grey" orient="auto">
          <path d="M 2 0 L 10 5 L 2 10 L 5 5 z" />
        </marker>
      </defs>
      <g id="arrow_svg" fill="none" stroke="gray" stroke-width="2" marker-end="url(#arrowhead)">
      </g>
    </svg>

    {{ grid_content | safe}}
</div>
</div>

<div id="measurement_window" class="sidecontainer">
    <button id="measurement_window_close_btn" onclick="hide_measurements()">close</button>
    <iframe id="measurement_iframe" src="{% url 'basic_ui:measurements_empty' %}">loading measurements...</iframe>
</div>

{% endblock %}


{% block extra_scripts %}
    <script type="text/javascript">
        function hide_measurements() {
            const measurement_window = document.getElementById("measurement_window");
            measurement_window.style.display = "none";
            curr_highlighted.style.backgroundColor = null;
            curr_highlighted = null;
        }
        function show_measurements() {
            const measurement_window = document.getElementById("measurement_window");
            measurement_window.style.display = "block";
        }

        var curr_highlighted = null;

        function click_handler(elem, target_url) {
            if (curr_highlighted !== elem) {
                const meas_iframe = document.getElementById("measurement_iframe");
                if (curr_highlighted != null) {
                    curr_highlighted.style.backgroundColor = null;
                }
                curr_highlighted = elem;
                const color_str = window.getComputedStyle(elem).borderColor;
                // this is a bit of a hack to make the color transparent
                elem.style.backgroundColor = color_str.replace("rgb", "rgba").replace(")", ", 0.2)");
                meas_iframe.src = target_url;
            }
            show_measurements();
        }

        function drawConnector(src_id, dst_id) {
          const src = document.getElementById(src_id);
          const dst = document.getElementById(dst_id);
          const svg = document.getElementById("arrow_svg");
          const arrow = document.createElementNS("http://www.w3.org/2000/svg", "path");

          const src_pos = {
            x: src.offsetLeft + src.offsetWidth / 2,
            y: src.offsetTop + src.offsetHeight
          };
          const dst_pos = {
            x: dst.offsetLeft + dst.offsetWidth / 2,
            y: dst.offsetTop - 5
          };
          const d_str =
              "M " + (src_pos.x) + " " + (src_pos.y) + " " +
              "C " +
              (src_pos.x) + " " + (src_pos.y + 20) + "," +
              (dst_pos.x) + " " + (dst_pos.y - 30) + "," +
              (dst_pos.x) + " " + (dst_pos.y);
          arrow.setAttribute("d", d_str);

          svg.appendChild(arrow);
        };

        document.addEventListener("DOMContentLoaded", function(event){
                    {{ connector_js | safe }}
        });
    </script>
{% endblock %}